### ISSUE TITLE
Won't copy on linux

### ISSUE THREAD

**Issue by episanty** [halirutan/Mathematica-SE-Tools#1]
For the last few months, I've been unable to get the palette to put stuff on the clipboard. It works mostly as normal (i.e. it does everything it used to, including e.g. put stuff in history and so on) but it when it's done the image doesn't make it to the clipboard.

I just re-installed the palette and I'm running version 10.0 for Linux x86 (64-bit) (December 4, 2014), running on Ubuntu 16.04. I'm happy to help diagnose this further.

**Comment by halirutan** [comment]
> For the last few months, I've been unable to get the palette to put stuff on the clipboard.

Well, this is like having a mole and not going to the doctor for far too long :)

To copy code to the clipboard, I'm using the following function

```
copyToClipboard[text_] := If[
   $VersionNumber >= 10,
   CopyToClipboard[text],
   Module[{nb}, nb = NotebookCreate[Visible -> False];
    NotebookWrite[nb, Cell[text, "Input"]];
    SelectionMove[nb, All, Notebook];
    FrontEndTokenExecute[nb, "Copy"];
    NotebookClose[nb];]
   ];
```

As you can see with version 10, I started using `CopyToClipboard` because the old way of creating an invisible notebook and copy its content doesn't work correctly for later versions. Would you be able to test this with `copyToClipboard["Hell"]` and if it doesn't work, reduce the version number in the condition to 9?

**Comment by episanty** [comment]
> Well, this is like having a mole and not going to the doctor for far too long :)

Yeah, probably, but what can I say? =P.

-----

I tested the given `copyToClipboard` but all it does is empty the clipboard - but then, that's what `CopyToClipboard` does, to begin with. Weirdly enough, the alternative does work.

This probably means the issue is deeper (this is MM v10.0.2 in case the .2 changes anything) but maybe this can be sidestepped by adding an override option to that conditional? Say, something like

     If[$VersionNumber >= 10 && FE`SETools`$copyToClipboardCludge ===True, ··· ]

=P

**Comment by halirutan** [comment]
I'm not sure why we haven't resolved this issue here, but I guess we discussed this in chat and I just forgot to close it.

Besides the fact that the upload is now broken entirely, did copying work for you since aehm.. 2017?

**Comment by episanty** [comment]
I.... have no idea. I'm pretty sure I've been able to use the palette on my linux desktop without any copy-paste issues in the intervening time. I have no idea whether I was involved in its resolution or whether it just fixed itself without me noticing it or remembering that it was an issue.

I unfortunately have no access to that linux desktop until the world goes back to normal.

**Comment by halirutan** [comment]
Alright, I don't remember either :)
